name: Style Modified Files

on:
  pull_request_target: # Triggers when code is pushed to a PR's target branch
    types: [opened, synchronize, reopened]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diff

      - name: Delete .Rprofile (if present)
        run: if [ -f .Rprofile ]; then rm .Rprofile; fi

      - name: Install R 
        uses: r-lib/actions/setup-r@v2

      - name: Install styler
        run: install.packages("styler")
        shell: Rscript {0}

      - name: Get modified files
        id: changed_files
        run: |
          git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} > modified_files.txt
          echo "::set-output name=modified::$(cat modified_files.txt)"

      - name: Style modified R files
        if: ${{ steps.changed_files.outputs.modified }}
        run: Rscript -e 'library(styler); styler::style_file(readLines("modified_files.txt"))'
