name: Style Modified Files

on:
  pull_request_target: # Triggers when code is pushed to a PR's target branch
    types: [opened, synchronize, reopened]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install R 
        uses: r-lib/actions/setup-r@v2

      - name: Install styling dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::gh
            any::styler
            any::purrr
          needs: check

      - name: Style modified R files
        run: |
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed_files <- purrr::map_chr(files, "filename")
          all_files <- list.files(recursive = TRUE)
          exclusions_list <- as.list(setdiff(all_files, changed_files))
          styler::style_dir(".", exclude_files = exclusions_list)
        shell: Rscript {0}
